environment:
  matrix:
  - nodejs_version: "stable"

branches:
  only:
  - master

skip_tags: true

max_jobs: 4

clone_depth: 50

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version

before_test:
  - ps: $wait = Start-Process -PassThru node .\wait.js

test_script:
  - npm run test

after_test:
  - ps: Stop-Process -InputObject $wait
  - type .\out.txt

build: off

deploy: off
