environment:
  matrix:
  - nodejs_version: "stable"

branches:
  only:
  - master

skip_tags: true

max_jobs: 4

clone_depth: 50

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

before_test:
  - ps: Start-Process node wait.js

test_script:
  - npm run test

after_test:
  - cmd: type .\out.txt
  - cmd: dir
  - cmd: node kill.js
  - cmd: type .\out.txt
  - cmd: dir

#  - ps: Stop-Process -InputObject $wait

build: off

deploy: off
